# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_dice.ipynb.

# %% auto 0
__all__ = ['throw']

# %% ../nbs/00_dice.ipynb 5
def throw(N:int, # number of sides on the dice
         inhand:int = 1): # number of dice in hand
    result = rng.integers(low=1, high=N+1, size=inhand)
    return result.sum(), result
    
