VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('16')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('37')
MAJOR_VERSION = 1
MINOR_VERSION = 8
PATCH_VERSION = 202212161037
version_date = '2022/12/16 10:37'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
