# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iva/makenet/proto/regularizer_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iva/makenet/proto/regularizer_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n*iva/makenet/proto/regularizer_config.proto\"X\n\tRegConfig\x12\x12\n\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n\x05scope\x18\x02 \x01(\tR\x05scope\x12!\n\x0cweight_decay\x18\x03 \x01(\x02R\x0bweightDecayb\x06proto3')
)




_REGCONFIG = _descriptor.Descriptor(
  name='RegConfig',
  full_name='RegConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='RegConfig.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='type', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scope', full_name='RegConfig.scope', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='scope', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight_decay', full_name='RegConfig.weight_decay', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='weightDecay', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['RegConfig'] = _REGCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegConfig = _reflection.GeneratedProtocolMessageType('RegConfig', (_message.Message,), dict(
  DESCRIPTOR = _REGCONFIG,
  __module__ = 'iva.makenet.proto.regularizer_config_pb2'
  # @@protoc_insertion_point(class_scope:RegConfig)
  ))
_sym_db.RegisterMessage(RegConfig)


# @@protoc_insertion_point(module_scope)
