
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T19:15:12-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "8cd12a7ae1fd7662aae7f04228f65d3fa1582050",
 "version": "0.0.150"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
