
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-14T12:24:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "71e3347aa8f81519b2079bc75c64250510ba3391",
 "version": "0.3.8rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
