
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T16:42:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a31e79829ce1a46d8d5c1da9e082eca7d99da33",
 "version": "0.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
