
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-14T17:14:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b165ea06cb044c15addbdece13feb314d43d0e7",
 "version": "2.8.9.dev20221215"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
