import yaml
from _typeshed import Incomplete

class _SchemaLoader(yaml.loader.SafeLoader): ...

def yaml_load_data(data, *, private: bool = ...): ...
def yaml_load_file(filename, *, private: bool = ...): ...
def yaml_load(*, data: Incomplete | None = ..., filename: Incomplete | None = ..., private: bool = ...): ...

class _SchemaDumper(yaml.dumper.SafeDumper): ...

def yaml_dump(data, *, filename: Incomplete | None = ...): ...
