
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T13:23:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "74d1dd55c9390b3f4149143be481aff22408995f",
 "version": "1.99"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
