
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-14T16:01:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6bbb97be243afecc991880be0963fb4016c5833d",
 "version": "0.2.55.post0.dev8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
