
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T16:47:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "957dc5eac9e2e8d1783c638f0692e72af90937a0",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
