# Generated by Django 4.0.8 on 2022-12-04 16:02

from django.db import migrations, models
import django.db.models.deletion
import django_group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="configs",
                        serialize=False,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=django_group.models.image_directory_path,
                        verbose_name="Avatar of group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Config",
                "verbose_name_plural": "Configs",
                "db_table": "auth_group_config",
            },
        ),
    ]
