
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-18T21:48:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d815c70080509fe17f2312c42f93ad85f99f60c",
 "version": "v2.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
