
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-14T13:02:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b94a39bf18f93ef56fc153e0644bdbfe7cdd26a",
 "version": "0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
