DATA_SCHEMA_V1 = "kubefox.proto.v1.KubeFoxData"
PROTOBUF_CONTENT_TYPE = "application/protobuf"

COMPONENT_REQUEST_TYPE = "io.kubefox.component_request"
COMPONENT_RESPONSE_TYPE = "io.kubefox.component_response"
CRON_REQUEST_TYPE = "io.kubefox.cron_request"
CRON_RESPONSE_TYPE = "io.kubefox.cron_response"
DAPR_REQUEST_TYPE = "io.kubefox.dapr_request"
DAPR_RESPONSE_TYPE = "io.kubefox.dapr_response"
HEALTH_REQUEST_TYPE = "io.kubefox.health_request"
HEALTH_RESPONSE_TYPE = "io.kubefox.health_response"
HTTP_REQUEST_TYPE = "io.kubefox.http_request"
HTTP_RESPONSE_TYPE = "io.kubefox.http_response"
KUBERNETES_REQUEST_TYPE = "io.kubefox.kubernetes_request"
KUBERNETES_RESPONSE_TYPE = "io.kubefox.kubernetes_response"
METRICS_REQUEST_TYPE = "io.kubefox.metrics_request"
METRICS_RESPONSE_TYPE = "io.kubefox.metrics_response"
TELEMETRY_REQUEST_TYPE = "io.kubefox.telemetry_request"
TELEMETRY_RESPONSE_TYPE = "io.kubefox.telemetry_response"

ERROR_RESPONSE_TYPE = "io.kubefox.error"
REJECTED_RESPONSE_TYPE = "io.kubefox.rejected"
