# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import kubefox_pb2 as kubefox__pb2


class ComponentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InvokeRemoteComponent = channel.unary_unary(
                '/kubefox.proto.v1.ComponentService/InvokeRemoteComponent',
                request_serializer=kubefox__pb2.Request.SerializeToString,
                response_deserializer=kubefox__pb2.Data.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/kubefox.proto.v1.ComponentService/Subscribe',
                request_serializer=kubefox__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=kubefox__pb2.Data.FromString,
                )
        self.Unsubscribe = channel.unary_unary(
                '/kubefox.proto.v1.ComponentService/Unsubscribe',
                request_serializer=kubefox__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=kubefox__pb2.Ack.FromString,
                )
        self.SendResponse = channel.unary_unary(
                '/kubefox.proto.v1.ComponentService/SendResponse',
                request_serializer=kubefox__pb2.Response.SerializeToString,
                response_deserializer=kubefox__pb2.Ack.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/kubefox.proto.v1.ComponentService/GetConfig',
                request_serializer=kubefox__pb2.ConfigRequest.SerializeToString,
                response_deserializer=kubefox__pb2.ConfigResponse.FromString,
                )


class ComponentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InvokeRemoteComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComponentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InvokeRemoteComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeRemoteComponent,
                    request_deserializer=kubefox__pb2.Request.FromString,
                    response_serializer=kubefox__pb2.Data.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=kubefox__pb2.SubscribeRequest.FromString,
                    response_serializer=kubefox__pb2.Data.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=kubefox__pb2.SubscribeRequest.FromString,
                    response_serializer=kubefox__pb2.Ack.SerializeToString,
            ),
            'SendResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendResponse,
                    request_deserializer=kubefox__pb2.Response.FromString,
                    response_serializer=kubefox__pb2.Ack.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=kubefox__pb2.ConfigRequest.FromString,
                    response_serializer=kubefox__pb2.ConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kubefox.proto.v1.ComponentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComponentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InvokeRemoteComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubefox.proto.v1.ComponentService/InvokeRemoteComponent',
            kubefox__pb2.Request.SerializeToString,
            kubefox__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/kubefox.proto.v1.ComponentService/Subscribe',
            kubefox__pb2.SubscribeRequest.SerializeToString,
            kubefox__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubefox.proto.v1.ComponentService/Unsubscribe',
            kubefox__pb2.SubscribeRequest.SerializeToString,
            kubefox__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubefox.proto.v1.ComponentService/SendResponse',
            kubefox__pb2.Response.SerializeToString,
            kubefox__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubefox.proto.v1.ComponentService/GetConfig',
            kubefox__pb2.ConfigRequest.SerializeToString,
            kubefox__pb2.ConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/kubefox.proto.v1.ControllerService/Invoke',
                request_serializer=kubefox__pb2.Data.SerializeToString,
                response_deserializer=kubefox__pb2.Data.FromString,
                )


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=kubefox__pb2.Data.FromString,
                    response_serializer=kubefox__pb2.Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kubefox.proto.v1.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kubefox.proto.v1.ControllerService/Invoke',
            kubefox__pb2.Data.SerializeToString,
            kubefox__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
