
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T11:30:21+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ac3c5a9a77815469ce7a65edf5e30b5c0404501",
 "version": "1.13.79"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
