
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-18T21:41:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ef1036ae80ee2606df63cf3be5ce90469960e25b",
 "version": "v2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
