
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T13:47:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "be4f16741dfacdcd6dde72e02605c46ce93429b1",
 "version": "4.7.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
