
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T14:15:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "32b3707dd122d5a4bedbc898a2a7dc90090289d6",
 "version": "4.7.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
