
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-18T15:13:59-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "864cefb1f051358d6968c6721f2cfd065e95acfb",
 "version": "0.0.151"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
