
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-12T18:10:10+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "43ab925c0dc7b42c83b45c49ab8bb763227b2081",
 "version": "0.1.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
