
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T16:16:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd4505b5129b3639ba4a5366fc91e1a71e90ab8e",
 "version": "7.19.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
