
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-06T10:43:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4679d890dc7b1d10bb2e38fb0d9d7e26526f3b9",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
