# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.0.5'
git_version = '69b8bfd90971380c8d24f4502144eff95d4761c0'
