
# This file was generated by 'versioneer.py' (0.23.dev0) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T15:07:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "94f3f32374dcfce7324d296be973f3f5445ea413",
 "version": "2.8.9.dev20221214"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
