from pathlib import Path

PROJECT_DIR = Path(__file__).parent.parent
TESTS_DIR = PROJECT_DIR / "tests"

INPUT_FILES_DIR = TESTS_DIR / "input_files"
REQUIREMENTS_IN_PATH = INPUT_FILES_DIR / "requirements.in"
REQUIREMENTS_OUT_PATH = INPUT_FILES_DIR / "requirements.txt"
REQUIREMENTS_MULTIPLATFORM_DIR = INPUT_FILES_DIR / "multi-platform"
REQUIREMENTS_MULTIPLATFORM_OUT_PATH = (
    REQUIREMENTS_MULTIPLATFORM_DIR / "requirements-3.7-win32-Windows-AMD64.txt"
)
REQUIREMENTS_MULTIPLATFORM_CONFIG_PATH = REQUIREMENTS_MULTIPLATFORM_DIR / "mvenv.yaml"
REQUIREMENTS_MULTIPLATFORM_REQUIREMENTS_IN_PATH = (
    REQUIREMENTS_MULTIPLATFORM_DIR / "requirements.in"
)
BASIC_CONFIG_PATH = INPUT_FILES_DIR / "mvenv.yaml"
BASIC_REQUIREMENTS_HASH = "0158dc37fee8f2657ed524b9d2c46ddc"
BASIC_STATE_CONFIG_PATH = INPUT_FILES_DIR / "mvenv-state.json"
EPHEMERAL_CONFIG_PATH = INPUT_FILES_DIR / "ephemeral" / "mvenv.yaml"
HOOKS_CONFIG_PATH = INPUT_FILES_DIR / "hooks" / "mvenv.yaml"
UPGRADE_FILES_DIR = INPUT_FILES_DIR / "upgrade"
UPGRADE_REQUIREMENTS_IN_PATH = UPGRADE_FILES_DIR / "requirements.in"
UPGRADE_REQUIREMENTS_OUT_PATH = UPGRADE_FILES_DIR / "requirements.txt"
AUTO_SYNC_CHANGED_CONFIG_PATH = INPUT_FILES_DIR / "auto_sync_changed" / "mvenv.yaml"
