
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T17:00:10-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b87deaddb9fc32fea0bf085a78b772e065535d1a",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
