
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-18T02:19:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7106b4989b7d25af3955e7ccd5f77e25f39a11b9",
 "version": "0.5.dev2251"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
