
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T16:24:59-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fb17cec3c716d4603ee91c87862a1db6842b794",
 "version": "2.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
