# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iva/detectnet_v2/proto/early_stopping_annealing_schedule_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iva/detectnet_v2/proto/early_stopping_annealing_schedule_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\nEiva/detectnet_v2/proto/early_stopping_annealing_schedule_config.proto\"\xfc\x01\n$EarlyStoppingAnnealingScheduleConfig\x12*\n\x11min_learning_rate\x18\x01 \x01(\x02R\x0fminLearningRate\x12*\n\x11max_learning_rate\x18\x02 \x01(\x02R\x0fmaxLearningRate\x12*\n\x11soft_start_epochs\x18\x03 \x01(\rR\x0fsoftStartEpochs\x12)\n\x10\x61nnealing_epochs\x18\x04 \x01(\rR\x0f\x61nnealingEpochs\x12%\n\x0epatience_steps\x18\x05 \x01(\rR\rpatienceStepsb\x06proto3')
)




_EARLYSTOPPINGANNEALINGSCHEDULECONFIG = _descriptor.Descriptor(
  name='EarlyStoppingAnnealingScheduleConfig',
  full_name='EarlyStoppingAnnealingScheduleConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_learning_rate', full_name='EarlyStoppingAnnealingScheduleConfig.min_learning_rate', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='minLearningRate', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_learning_rate', full_name='EarlyStoppingAnnealingScheduleConfig.max_learning_rate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='maxLearningRate', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='soft_start_epochs', full_name='EarlyStoppingAnnealingScheduleConfig.soft_start_epochs', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='softStartEpochs', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='annealing_epochs', full_name='EarlyStoppingAnnealingScheduleConfig.annealing_epochs', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='annealingEpochs', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patience_steps', full_name='EarlyStoppingAnnealingScheduleConfig.patience_steps', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='patienceSteps', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=326,
)

DESCRIPTOR.message_types_by_name['EarlyStoppingAnnealingScheduleConfig'] = _EARLYSTOPPINGANNEALINGSCHEDULECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EarlyStoppingAnnealingScheduleConfig = _reflection.GeneratedProtocolMessageType('EarlyStoppingAnnealingScheduleConfig', (_message.Message,), dict(
  DESCRIPTOR = _EARLYSTOPPINGANNEALINGSCHEDULECONFIG,
  __module__ = 'iva.detectnet_v2.proto.early_stopping_annealing_schedule_config_pb2'
  # @@protoc_insertion_point(class_scope:EarlyStoppingAnnealingScheduleConfig)
  ))
_sym_db.RegisterMessage(EarlyStoppingAnnealingScheduleConfig)


# @@protoc_insertion_point(module_scope)
