
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T20:52:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a7fb94147d69ad29bf753a210e684bba458ecf1",
 "version": "0.2.55.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
