DRC_VERSION = (0, 0, 11)

PATIENTS_API_VERSION = (0, 0, 11)
APPOINTMENTS_API_VERSION = (0, 0, 9)
DOCUMENTS_API_VERSION = (0, 0, 9)
MEDICATIONS_API_VERSION = (0, 0, 9)

USERS_API_VERSION = (0, 0, 9)
DOCTORS_API_VERSION = (0, 0, 9)

