
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T13:21:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c2c28929ac254f28bf4d8297f16b2edfe710147",
 "version": "0.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
