
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T06:15:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "045f85d5019d146eb1e7c14ba817e8e4ee1adfa3",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
