
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T12:55:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a666a29c1896ea63160c47f601776b5059d7815",
 "version": "0.1.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
