
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T23:24:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8933ecff4f9a3467d6beb30d520ca0668a5faa26",
 "version": "0.2.55.post0.dev38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
