
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T21:04:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9c0de51f4c69050a80d77a89f1dc7ab86afa5040",
 "version": "0.2.55.post0.dev18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
