# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iva/common/proto/nms_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iva/common/proto/nms_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!iva/common/proto/nms_config.proto\"\xe0\x01\n\tNMSConfig\x12\x31\n\x14\x63onfidence_threshold\x18\x01 \x01(\x02R\x13\x63onfidenceThreshold\x12\x38\n\x18\x63lustering_iou_threshold\x18\x02 \x01(\x02R\x16\x63lusteringIouThreshold\x12\x13\n\x05top_k\x18\x03 \x01(\rR\x04topK\x12/\n\x14infer_nms_score_bits\x18\x04 \x01(\rR\x11inferNmsScoreBits\x12 \n\x0c\x66orce_on_cpu\x18\x05 \x01(\x08R\nforceOnCpub\x06proto3')
)




_NMSCONFIG = _descriptor.Descriptor(
  name='NMSConfig',
  full_name='NMSConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence_threshold', full_name='NMSConfig.confidence_threshold', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='confidenceThreshold', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clustering_iou_threshold', full_name='NMSConfig.clustering_iou_threshold', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='clusteringIouThreshold', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_k', full_name='NMSConfig.top_k', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='topK', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='infer_nms_score_bits', full_name='NMSConfig.infer_nms_score_bits', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='inferNmsScoreBits', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='force_on_cpu', full_name='NMSConfig.force_on_cpu', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='forceOnCpu', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=262,
)

DESCRIPTOR.message_types_by_name['NMSConfig'] = _NMSCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NMSConfig = _reflection.GeneratedProtocolMessageType('NMSConfig', (_message.Message,), dict(
  DESCRIPTOR = _NMSCONFIG,
  __module__ = 'iva.common.proto.nms_config_pb2'
  # @@protoc_insertion_point(class_scope:NMSConfig)
  ))
_sym_db.RegisterMessage(NMSConfig)


# @@protoc_insertion_point(module_scope)
