# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iva/unet/proto/model_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iva/unet/proto/model_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!iva/unet/proto/model_config.proto\"\x9c\t\n\x0bModelConfig\x12\x32\n\x15pretrained_model_file\x18\x01 \x01(\tR\x13pretrainedModelFile\x12\x38\n\x18\x66reeze_pretrained_layers\x18\x02 \x01(\x08R\x16\x66reezePretrainedLayers\x12\x45\n\x1f\x61llow_loaded_model_modification\x18\x03 \x01(\x08R\x1c\x61llowLoadedModelModification\x12\x1d\n\nnum_layers\x18\x04 \x01(\x05R\tnumLayers\x12\x1f\n\x0buse_pooling\x18\x05 \x01(\x08R\nusePooling\x12$\n\x0euse_batch_norm\x18\x06 \x01(\x08R\x0cuseBatchNorm\x12\x1f\n\x0bremove_head\x18# \x01(\x08R\nremoveHead\x12\x1d\n\nbyom_model\x18\x1f \x01(\tR\tbyomModel\x12!\n\x0c\x64ropout_rate\x18\x07 \x01(\x02R\x0b\x64ropoutRate\x12\x1e\n\nactivation\x18\x15 \x01(\tR\nactivation\x12M\n\x12training_precision\x18\n \x01(\x0b\x32\x1e.ModelConfig.TrainingPrecisionR\x11trainingPrecision\x12\x1b\n\tfreeze_bn\x18\x0b \x01(\x08R\x08\x66reezeBn\x12#\n\rfreeze_blocks\x18\x0c \x03(\x02R\x0c\x66reezeBlocks\x12\x12\n\x04\x61rch\x18\r \x01(\tR\x04\x61rch\x12\x1d\n\nload_graph\x18\x0e \x01(\x08R\tloadGraph\x12\'\n\x0f\x61ll_projections\x18\x0f \x01(\x08R\x0e\x61llProjections\x12\x1d\n\nenable_qat\x18\x1d \x01(\x08R\tenableQat\x12,\n\x12model_input_height\x18\x10 \x01(\x05R\x10modelInputHeight\x12*\n\x11model_input_width\x18\x11 \x01(\x05R\x0fmodelInputWidth\x12\x30\n\x14model_input_channels\x18\x13 \x01(\x05R\x12modelInputChannels\x12*\n\x11pruned_model_path\x18\x14 \x01(\tR\x0fprunedModelPath\x12@\n\x0binitializer\x18\x17 \x01(\x0e\x32\x1e.ModelConfig.KernelInitializerR\x0binitializer\x1a\xa0\x01\n\x11TrainingPrecision\x12S\n\x0e\x62\x61\x63kend_floatx\x18\x01 \x01(\x0e\x32,.ModelConfig.TrainingPrecision.BackendFloatxR\rbackendFloatx\"6\n\rBackendFloatx\x12\x0b\n\x07INVALID\x10\x00\x12\x0b\n\x07\x46LOAT16\x10\x01\x12\x0b\n\x07\x46LOAT32\x10\x02\"F\n\x11KernelInitializer\x12\x12\n\x0eGLOROT_UNIFORM\x10\x00\x12\r\n\tHE_NORMAL\x10\x01\x12\x0e\n\nHE_UNIFORM\x10\x02\x62\x06proto3')
)



_MODELCONFIG_TRAININGPRECISION_BACKENDFLOATX = _descriptor.EnumDescriptor(
  name='BackendFloatx',
  full_name='ModelConfig.TrainingPrecision.BackendFloatx',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT16', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT32', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1092,
  serialized_end=1146,
)
_sym_db.RegisterEnumDescriptor(_MODELCONFIG_TRAININGPRECISION_BACKENDFLOATX)

_MODELCONFIG_KERNELINITIALIZER = _descriptor.EnumDescriptor(
  name='KernelInitializer',
  full_name='ModelConfig.KernelInitializer',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GLOROT_UNIFORM', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HE_NORMAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HE_UNIFORM', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1148,
  serialized_end=1218,
)
_sym_db.RegisterEnumDescriptor(_MODELCONFIG_KERNELINITIALIZER)


_MODELCONFIG_TRAININGPRECISION = _descriptor.Descriptor(
  name='TrainingPrecision',
  full_name='ModelConfig.TrainingPrecision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backend_floatx', full_name='ModelConfig.TrainingPrecision.backend_floatx', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='backendFloatx', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODELCONFIG_TRAININGPRECISION_BACKENDFLOATX,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=986,
  serialized_end=1146,
)

_MODELCONFIG = _descriptor.Descriptor(
  name='ModelConfig',
  full_name='ModelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pretrained_model_file', full_name='ModelConfig.pretrained_model_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='pretrainedModelFile', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freeze_pretrained_layers', full_name='ModelConfig.freeze_pretrained_layers', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='freezePretrainedLayers', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allow_loaded_model_modification', full_name='ModelConfig.allow_loaded_model_modification', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='allowLoadedModelModification', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_layers', full_name='ModelConfig.num_layers', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='numLayers', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_pooling', full_name='ModelConfig.use_pooling', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='usePooling', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_batch_norm', full_name='ModelConfig.use_batch_norm', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='useBatchNorm', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remove_head', full_name='ModelConfig.remove_head', index=6,
      number=35, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='removeHead', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='byom_model', full_name='ModelConfig.byom_model', index=7,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='byomModel', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dropout_rate', full_name='ModelConfig.dropout_rate', index=8,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='dropoutRate', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation', full_name='ModelConfig.activation', index=9,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='activation', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training_precision', full_name='ModelConfig.training_precision', index=10,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='trainingPrecision', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freeze_bn', full_name='ModelConfig.freeze_bn', index=11,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='freezeBn', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='freeze_blocks', full_name='ModelConfig.freeze_blocks', index=12,
      number=12, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='freezeBlocks', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arch', full_name='ModelConfig.arch', index=13,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='arch', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_graph', full_name='ModelConfig.load_graph', index=14,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='loadGraph', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_projections', full_name='ModelConfig.all_projections', index=15,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='allProjections', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_qat', full_name='ModelConfig.enable_qat', index=16,
      number=29, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='enableQat', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_input_height', full_name='ModelConfig.model_input_height', index=17,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='modelInputHeight', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_input_width', full_name='ModelConfig.model_input_width', index=18,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='modelInputWidth', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_input_channels', full_name='ModelConfig.model_input_channels', index=19,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='modelInputChannels', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pruned_model_path', full_name='ModelConfig.pruned_model_path', index=20,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='prunedModelPath', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initializer', full_name='ModelConfig.initializer', index=21,
      number=23, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='initializer', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODELCONFIG_TRAININGPRECISION, ],
  enum_types=[
    _MODELCONFIG_KERNELINITIALIZER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=1218,
)

_MODELCONFIG_TRAININGPRECISION.fields_by_name['backend_floatx'].enum_type = _MODELCONFIG_TRAININGPRECISION_BACKENDFLOATX
_MODELCONFIG_TRAININGPRECISION.containing_type = _MODELCONFIG
_MODELCONFIG_TRAININGPRECISION_BACKENDFLOATX.containing_type = _MODELCONFIG_TRAININGPRECISION
_MODELCONFIG.fields_by_name['training_precision'].message_type = _MODELCONFIG_TRAININGPRECISION
_MODELCONFIG.fields_by_name['initializer'].enum_type = _MODELCONFIG_KERNELINITIALIZER
_MODELCONFIG_KERNELINITIALIZER.containing_type = _MODELCONFIG
DESCRIPTOR.message_types_by_name['ModelConfig'] = _MODELCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfig = _reflection.GeneratedProtocolMessageType('ModelConfig', (_message.Message,), dict(

  TrainingPrecision = _reflection.GeneratedProtocolMessageType('TrainingPrecision', (_message.Message,), dict(
    DESCRIPTOR = _MODELCONFIG_TRAININGPRECISION,
    __module__ = 'iva.unet.proto.model_config_pb2'
    # @@protoc_insertion_point(class_scope:ModelConfig.TrainingPrecision)
    ))
  ,
  DESCRIPTOR = _MODELCONFIG,
  __module__ = 'iva.unet.proto.model_config_pb2'
  # @@protoc_insertion_point(class_scope:ModelConfig)
  ))
_sym_db.RegisterMessage(ModelConfig)
_sym_db.RegisterMessage(ModelConfig.TrainingPrecision)


# @@protoc_insertion_point(module_scope)
