# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iva/mask_rcnn/proto/data_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iva/mask_rcnn/proto/data_config.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%iva/mask_rcnn/proto/data_config.proto\"\x95\x04\n\nDataConfig\x12\x1d\n\nimage_size\x18\x01 \x01(\tR\timageSize\x12,\n\x12\x61ugment_input_data\x18\x02 \x01(\x08R\x10\x61ugmentInputData\x12\x1f\n\x0bnum_classes\x18\x03 \x01(\rR\nnumClasses\x12;\n\x1askip_crowd_during_training\x18\x04 \x01(\x08R\x17skipCrowdDuringTraining\x12\x32\n\x15training_file_pattern\x18\x06 \x01(\tR\x13trainingFilePattern\x12\x36\n\x17validation_file_pattern\x18\x07 \x01(\tR\x15validationFilePattern\x12\"\n\rval_json_file\x18\x08 \x01(\tR\x0bvalJsonFile\x12!\n\x0c\x65val_samples\x18\t \x01(\rR\x0b\x65valSamples\x12\x30\n\x14prefetch_buffer_size\x18\n \x01(\rR\x12prefetchBufferSize\x12.\n\x13shuffle_buffer_size\x18\x0b \x01(\rR\x11shuffleBufferSize\x12\x1b\n\tn_workers\x18\x0c \x01(\rR\x08nWorkers\x12*\n\x11max_num_instances\x18\r \x01(\rR\x0fmaxNumInstancesb\x06proto3')
)




_DATACONFIG = _descriptor.Descriptor(
  name='DataConfig',
  full_name='DataConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_size', full_name='DataConfig.image_size', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='imageSize', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='augment_input_data', full_name='DataConfig.augment_input_data', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='augmentInputData', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_classes', full_name='DataConfig.num_classes', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='numClasses', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skip_crowd_during_training', full_name='DataConfig.skip_crowd_during_training', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='skipCrowdDuringTraining', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training_file_pattern', full_name='DataConfig.training_file_pattern', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='trainingFilePattern', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validation_file_pattern', full_name='DataConfig.validation_file_pattern', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='validationFilePattern', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_json_file', full_name='DataConfig.val_json_file', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='valJsonFile', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eval_samples', full_name='DataConfig.eval_samples', index=7,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='evalSamples', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefetch_buffer_size', full_name='DataConfig.prefetch_buffer_size', index=8,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='prefetchBufferSize', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shuffle_buffer_size', full_name='DataConfig.shuffle_buffer_size', index=9,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='shuffleBufferSize', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_workers', full_name='DataConfig.n_workers', index=10,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='nWorkers', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_num_instances', full_name='DataConfig.max_num_instances', index=11,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='maxNumInstances', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=575,
)

DESCRIPTOR.message_types_by_name['DataConfig'] = _DATACONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataConfig = _reflection.GeneratedProtocolMessageType('DataConfig', (_message.Message,), dict(
  DESCRIPTOR = _DATACONFIG,
  __module__ = 'iva.mask_rcnn.proto.data_config_pb2'
  # @@protoc_insertion_point(class_scope:DataConfig)
  ))
_sym_db.RegisterMessage(DataConfig)


# @@protoc_insertion_point(module_scope)
