
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T13:10:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "02cc73763ee7c032f1f5f23a7e7fec17b97ee591",
 "version": "0.1.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
