
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T04:45:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "42bdfdd3ea4ec3dd1aaec7f76bf7b99dc80cdecd",
 "version": "0.2.55.post0.dev24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
