
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T12:28:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e935ecb7b09773c18fba04c14ec0293202d5783",
 "version": "1.98"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
