
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T13:40:00-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "03fb2c46f083c29ea94baeb6c7c79816e94d886e",
 "version": "4.7.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
