
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T10:21:09+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "75d2590d1dc082fa6c87c3e385a7f0e9f3d15c79",
 "version": "0.9.6.dev20221217"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
