CUSTOMER_ID = "customer_id"
BIRTHDAY = 'birthday'
CUSTOMER_CREATED_ON = 'customer_created_on'
CUSTOMER_MODIFIED_ON = 'customer_modified_on'
PAYTVPROVIDER_ID = 'paytvprovider_id'
INTERMEDIATE_RESULTS_DIRECTORY = "intermediate_results"
KMEANS_FEATURE = "kmeans"
MINIBATCH_KMEANS_FEATURE = "minibatch_kmeans"
CLUSTERING_NOISE_PT = -1
ENSEMBLE_IR1_PATH = "ensemble_ir1_algo_wise_results"
ENSEMBLE_IR2_PATH = "ensemble_ir2_user_cluster_members"
ENSEMBLE_IR3_PATH = "ensemble_ir3_top_user_cluster_members"
ENSEMBLE_IR4_PATH = "ensemble_ir4_birch_ensemble_results"
JSON_EXTENSION = ".json"
CSV_EXTENSION = ".csv"
NAN_DUMMY_FEATURE = "_nan"
TEMP_FILE = ".DS_Store"  # for macOS auto-generated file
S3_PAYTV_PREFIX = "paytv_"
S3_NONPAYTV_PREFIX = "no_paytv_"
GENDER = "gender"
LABEL = "label"
PROPERTIES = "properties"
CENTROID = "centroid"
IS_PAYTV = "is_paytv"
IS_PAY_TV = "is_pay_tv"
UD_KEY = 'UserDetail_UDKey'
GENDER_NAN = 'gender_nan'
CREATED_ON = 'created_on'
UPDATED_ON = 'updated_on'
DATE_TODAY = '2022-06-29T06:10:02.264518'
STATUS = "status"

VISIONPLUS_DEV = "visionplus-dev"
USER_CLUSTER_DIST = "data/database/user_profile/processed_data_for_an/user_cluster_dist.pkl"
PAY_TV_CENTROID_FEATURES = "data/historical/user/raw/mapping/31052022/Paytv_minibatch_kmeans_centroids_feature.csv"
PAY_TV_USER_CLUSTER_FEATURE = "data/historical/user/raw/mapping/31052022/Paytv_minibatch_kmeans_users_clustering_feature.csv"
NO_PAY_TV_USER_CLUSTER_FEATURE = 'data/historical/user/raw/mapping/31052022/No_paytv_minibatch_kmeans_users_clustering_feature.csv'
PAYTV_USER_CLUSTER_MAPPING_PATH = "data/historical/user/raw/mapping/31052022/paytv_minibatch_kmeans.csv"
NO_PAYTV_USER_CLUSTER_MAPPING_PATH = 'data/historical/user/raw/mapping/31052022/nonpaytv_minibatch_kmeans.csv'
PAY_TV_CLUSTER_CENTROID = 'data/historical/user/raw/mapping/31052022/Paytv_minibatch_kmeans_centroids.csv'
NO_PAY_TV_CLUSTER_CENTROID = 'data/historical/user/raw/mapping/31052022/No_paytv_minibatch_kmeans_centroids.csv'
CLUSTER_MODEL_PATH = "models/mapping/"
TFLITE_MODEL_PATH ='models/model_builder/model.tflite'
S3 = "s3"
GRAPH_DB = "graph_db"

MEAN_CLUSTER_DIST = "mean_cluster_dist"
MINIBATCH_KMEANS = "minibatch_kmeans"
DISTANCE_FROM_CENTROID = "distance_from_centroid"
USER_DETAIL_UDKEY = "UserDetail_UDKey"
TOD = "tod"
DURATION = "duration"

PAY_TV = "pay_tv"
NO_PAY_TV = "no_pay_tv"