VERSION_YEAR = 2022
VERSION_MONTH = int('12')
VERSION_DAY = int('15')
VERSION_HOUR = int('20')
VERSION_MINUTE = int('02')
MAJOR_VERSION = 1
MINOR_VERSION = 8
PATCH_VERSION = 202212152002
version_date = '2022/12/15 20:02'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
