
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-14T14:41:30+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a29ff93a992eb222f65ac5f9f2eb78cf8225133",
 "version": "1.0.9rc13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
