# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/./couchbase_version.py
# at
#    2022-12-08 17:25:46.162567
__version__ = '4.1.1'