
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T14:18:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c854693dc22720c09c110e3868627f377743793",
 "version": "1.100"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
