# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'gen'}

packages = \
['gsmtasks',
 'gsmtasks.components',
 'gsmtasks.components.schemas',
 'gsmtasks.paths',
 'gsmtasks.paths.account_roles_activate_create',
 'gsmtasks.paths.account_roles_create',
 'gsmtasks.paths.account_roles_destroy',
 'gsmtasks.paths.account_roles_list',
 'gsmtasks.paths.account_roles_notify_create',
 'gsmtasks.paths.account_roles_partial_update',
 'gsmtasks.paths.account_roles_retrieve',
 'gsmtasks.paths.account_roles_token_retrieve',
 'gsmtasks.paths.account_roles_update',
 'gsmtasks.paths.accounts_braintree_customer_retrieve',
 'gsmtasks.paths.accounts_change_owner_create',
 'gsmtasks.paths.accounts_list',
 'gsmtasks.paths.accounts_managers_create',
 'gsmtasks.paths.accounts_managers_destroy',
 'gsmtasks.paths.accounts_managers_retrieve',
 'gsmtasks.paths.accounts_partial_update',
 'gsmtasks.paths.accounts_retrieve',
 'gsmtasks.paths.accounts_stripe_attach_payment_method_update',
 'gsmtasks.paths.accounts_stripe_create_setup_intent_create',
 'gsmtasks.paths.accounts_stripe_create_setup_intent_update',
 'gsmtasks.paths.accounts_stripe_detach_payment_method_update',
 'gsmtasks.paths.accounts_stripe_get_payment_method_retrieve',
 'gsmtasks.paths.accounts_stripe_get_setup_attempt_retrieve',
 'gsmtasks.paths.accounts_stripe_get_setup_intent_retrieve',
 'gsmtasks.paths.accounts_stripe_payment_methods_retrieve',
 'gsmtasks.paths.accounts_stripe_set_default_payment_method_update',
 'gsmtasks.paths.accounts_stripe_setup_intents_retrieve',
 'gsmtasks.paths.accounts_update',
 'gsmtasks.paths.accounts_workers_create',
 'gsmtasks.paths.accounts_workers_destroy',
 'gsmtasks.paths.accounts_workers_retrieve',
 'gsmtasks.paths.addons_list',
 'gsmtasks.paths.addons_retrieve',
 'gsmtasks.paths.billing_customers_client_token_retrieve',
 'gsmtasks.paths.billing_customers_create',
 'gsmtasks.paths.billing_customers_list',
 'gsmtasks.paths.billing_customers_partial_update',
 'gsmtasks.paths.billing_customers_retrieve',
 'gsmtasks.paths.billing_customers_update',
 'gsmtasks.paths.billing_invoices_list',
 'gsmtasks.paths.billing_invoices_mark_as_paid_create',
 'gsmtasks.paths.billing_invoices_partial_update',
 'gsmtasks.paths.billing_invoices_retrieve',
 'gsmtasks.paths.billing_invoices_update',
 'gsmtasks.paths.billing_stripe_payments_list',
 'gsmtasks.paths.billing_stripe_payments_retrieve',
 'gsmtasks.paths.billing_transactions_list',
 'gsmtasks.paths.billing_transactions_retrieve',
 'gsmtasks.paths.client_roles_create',
 'gsmtasks.paths.client_roles_list',
 'gsmtasks.paths.client_roles_notify_create',
 'gsmtasks.paths.client_roles_partial_update',
 'gsmtasks.paths.client_roles_retrieve',
 'gsmtasks.paths.client_roles_update',
 'gsmtasks.paths.clients_create',
 'gsmtasks.paths.clients_list',
 'gsmtasks.paths.clients_partial_update',
 'gsmtasks.paths.clients_retrieve',
 'gsmtasks.paths.clients_update',
 'gsmtasks.paths.configurations_list',
 'gsmtasks.paths.contact_address_exports_list',
 'gsmtasks.paths.contact_address_import_create',
 'gsmtasks.paths.contact_address_import_list',
 'gsmtasks.paths.contact_address_import_retrieve',
 'gsmtasks.paths.contact_addresses_create',
 'gsmtasks.paths.contact_addresses_list',
 'gsmtasks.paths.contact_addresses_partial_update',
 'gsmtasks.paths.contact_addresses_retrieve',
 'gsmtasks.paths.contact_addresses_update',
 'gsmtasks.paths.devices_create',
 'gsmtasks.paths.devices_list',
 'gsmtasks.paths.devices_retrieve',
 'gsmtasks.paths.docs_schema_retrieve',
 'gsmtasks.paths.documents_batch_delete_create',
 'gsmtasks.paths.documents_create',
 'gsmtasks.paths.documents_destroy',
 'gsmtasks.paths.documents_list',
 'gsmtasks.paths.documents_retrieve',
 'gsmtasks.paths.emails_create',
 'gsmtasks.paths.emails_destroy',
 'gsmtasks.paths.emails_list',
 'gsmtasks.paths.emails_partial_update',
 'gsmtasks.paths.emails_resend_create',
 'gsmtasks.paths.emails_retrieve',
 'gsmtasks.paths.emails_update',
 'gsmtasks.paths.exports_create',
 'gsmtasks.paths.exports_destroy',
 'gsmtasks.paths.exports_list',
 'gsmtasks.paths.exports_partial_update',
 'gsmtasks.paths.exports_retrieve',
 'gsmtasks.paths.exports_update',
 'gsmtasks.paths.file_uploads_create',
 'gsmtasks.paths.file_uploads_list',
 'gsmtasks.paths.file_uploads_retrieve',
 'gsmtasks.paths.formrules_create',
 'gsmtasks.paths.formrules_destroy',
 'gsmtasks.paths.formrules_list',
 'gsmtasks.paths.formrules_partial_update',
 'gsmtasks.paths.formrules_retrieve',
 'gsmtasks.paths.formrules_update',
 'gsmtasks.paths.integrations_create',
 'gsmtasks.paths.metafields_create',
 'gsmtasks.paths.metafields_destroy',
 'gsmtasks.paths.metafields_list',
 'gsmtasks.paths.metafields_partial_update',
 'gsmtasks.paths.metafields_retrieve',
 'gsmtasks.paths.metafields_update',
 'gsmtasks.paths.notification_templates_create',
 'gsmtasks.paths.notification_templates_destroy',
 'gsmtasks.paths.notification_templates_list',
 'gsmtasks.paths.notification_templates_partial_update',
 'gsmtasks.paths.notification_templates_render_create',
 'gsmtasks.paths.notification_templates_retrieve',
 'gsmtasks.paths.notification_templates_update',
 'gsmtasks.paths.notifications_create',
 'gsmtasks.paths.notifications_list',
 'gsmtasks.paths.notifications_retrieve',
 'gsmtasks.paths.orders_list',
 'gsmtasks.paths.orders_partial_update',
 'gsmtasks.paths.orders_retrieve',
 'gsmtasks.paths.orders_update',
 'gsmtasks.paths.password_change_create',
 'gsmtasks.paths.password_reset_confirm_create',
 'gsmtasks.paths.password_reset_create',
 'gsmtasks.paths.push_notifications_create',
 'gsmtasks.paths.push_notifications_destroy',
 'gsmtasks.paths.push_notifications_list',
 'gsmtasks.paths.push_notifications_partial_update',
 'gsmtasks.paths.push_notifications_resend_create',
 'gsmtasks.paths.push_notifications_retrieve',
 'gsmtasks.paths.push_notifications_update',
 'gsmtasks.paths.recurrences_list',
 'gsmtasks.paths.recurrences_partial_update',
 'gsmtasks.paths.recurrences_retrieve',
 'gsmtasks.paths.recurrences_update',
 'gsmtasks.paths.register_create',
 'gsmtasks.paths.reports_tasks_states_count_retrieve',
 'gsmtasks.paths.reviews_create',
 'gsmtasks.paths.reviews_list',
 'gsmtasks.paths.reviews_retrieve',
 'gsmtasks.paths.route_optimizations_commit_create',
 'gsmtasks.paths.route_optimizations_create',
 'gsmtasks.paths.route_optimizations_list',
 'gsmtasks.paths.route_optimizations_results_retrieve',
 'gsmtasks.paths.route_optimizations_retrieve',
 'gsmtasks.paths.route_optimizations_routes_create',
 'gsmtasks.paths.route_optimizations_routes_retrieve',
 'gsmtasks.paths.route_optimizations_schedule_create',
 'gsmtasks.paths.routes_destroy',
 'gsmtasks.paths.routes_list',
 'gsmtasks.paths.routes_partial_update',
 'gsmtasks.paths.routes_retrieve',
 'gsmtasks.paths.routes_update',
 'gsmtasks.paths.scenes_dashboard_list',
 'gsmtasks.paths.scenes_order_list_list',
 'gsmtasks.paths.scenes_recurrence_list_list',
 'gsmtasks.paths.scenes_task_list_list',
 'gsmtasks.paths.signatures_batch_delete_create',
 'gsmtasks.paths.signatures_create',
 'gsmtasks.paths.signatures_destroy',
 'gsmtasks.paths.signatures_list',
 'gsmtasks.paths.signatures_retrieve',
 'gsmtasks.paths.sms_create',
 'gsmtasks.paths.sms_destroy',
 'gsmtasks.paths.sms_list',
 'gsmtasks.paths.sms_partial_update',
 'gsmtasks.paths.sms_resend_create',
 'gsmtasks.paths.sms_retrieve',
 'gsmtasks.paths.sms_update',
 'gsmtasks.paths.task_address_features_list',
 'gsmtasks.paths.task_address_features_retrieve',
 'gsmtasks.paths.task_commands_create',
 'gsmtasks.paths.task_commands_list',
 'gsmtasks.paths.task_commands_retrieve',
 'gsmtasks.paths.task_commands_update',
 'gsmtasks.paths.task_event_tracks_list',
 'gsmtasks.paths.task_event_tracks_retrieve',
 'gsmtasks.paths.task_events_list',
 'gsmtasks.paths.task_events_retrieve',
 'gsmtasks.paths.task_exports_list',
 'gsmtasks.paths.task_forms_create',
 'gsmtasks.paths.task_forms_destroy',
 'gsmtasks.paths.task_forms_list',
 'gsmtasks.paths.task_forms_partial_update',
 'gsmtasks.paths.task_forms_retrieve',
 'gsmtasks.paths.task_forms_update',
 'gsmtasks.paths.task_import_create',
 'gsmtasks.paths.task_import_list',
 'gsmtasks.paths.task_import_mapping_create',
 'gsmtasks.paths.task_import_mapping_list',
 'gsmtasks.paths.task_import_mapping_retrieve',
 'gsmtasks.paths.task_import_retrieve',
 'gsmtasks.paths.task_metadatas_list',
 'gsmtasks.paths.task_metadatas_retrieve',
 'gsmtasks.paths.tasks_accept_create',
 'gsmtasks.paths.tasks_account_change_create',
 'gsmtasks.paths.tasks_activate_create',
 'gsmtasks.paths.tasks_assign_create',
 'gsmtasks.paths.tasks_cancel_create',
 'gsmtasks.paths.tasks_complete_create',
 'gsmtasks.paths.tasks_create',
 'gsmtasks.paths.tasks_documents_retrieve',
 'gsmtasks.paths.tasks_events_retrieve',
 'gsmtasks.paths.tasks_fail_create',
 'gsmtasks.paths.tasks_list',
 'gsmtasks.paths.tasks_partial_update',
 'gsmtasks.paths.tasks_reject_create',
 'gsmtasks.paths.tasks_reorder_create',
 'gsmtasks.paths.tasks_reposition_create',
 'gsmtasks.paths.tasks_retrieve',
 'gsmtasks.paths.tasks_signatures_retrieve',
 'gsmtasks.paths.tasks_transit_create',
 'gsmtasks.paths.tasks_unaccept_create',
 'gsmtasks.paths.tasks_unassign_create',
 'gsmtasks.paths.tasks_update',
 'gsmtasks.paths.time_location_features_create',
 'gsmtasks.paths.time_location_features_destroy',
 'gsmtasks.paths.time_location_features_list',
 'gsmtasks.paths.time_location_features_partial_update',
 'gsmtasks.paths.time_location_features_retrieve',
 'gsmtasks.paths.time_location_features_update',
 'gsmtasks.paths.time_locations_create',
 'gsmtasks.paths.time_locations_list',
 'gsmtasks.paths.time_locations_retrieve',
 'gsmtasks.paths.trackers_create',
 'gsmtasks.paths.trackers_list',
 'gsmtasks.paths.trackers_partial_update',
 'gsmtasks.paths.trackers_public_retrieve',
 'gsmtasks.paths.trackers_retrieve',
 'gsmtasks.paths.trackers_update',
 'gsmtasks.paths.users_activate_create',
 'gsmtasks.paths.users_create',
 'gsmtasks.paths.users_destroy',
 'gsmtasks.paths.users_list',
 'gsmtasks.paths.users_on_duty_destroy',
 'gsmtasks.paths.users_on_duty_log_create',
 'gsmtasks.paths.users_on_duty_log_list',
 'gsmtasks.paths.users_on_duty_log_retrieve',
 'gsmtasks.paths.users_on_duty_retrieve',
 'gsmtasks.paths.users_on_duty_update',
 'gsmtasks.paths.users_partial_update',
 'gsmtasks.paths.users_retrieve',
 'gsmtasks.paths.users_update',
 'gsmtasks.paths.webhooks_active_create',
 'gsmtasks.paths.webhooks_create',
 'gsmtasks.paths.webhooks_destroy',
 'gsmtasks.paths.webhooks_inactive_create',
 'gsmtasks.paths.webhooks_list',
 'gsmtasks.paths.webhooks_partial_update',
 'gsmtasks.paths.webhooks_retrieve',
 'gsmtasks.paths.webhooks_update',
 'gsmtasks.paths.worker_features_list',
 'gsmtasks.paths.worker_features_retrieve',
 'gsmtasks.paths.worker_tracks_list',
 'gsmtasks.paths.working_state_create',
 'gsmtasks.paths.working_state_list',
 'gsmtasks.paths.working_state_retrieve']

package_data = \
{'': ['*']}

install_requires = \
['lapidary>=0.7.2,<0.8.0', 'platformdirs>=2.6.0,<3.0.0']

setup_kwargs = {
    'name': 'gsmtasks-client',
    'version': '0.4.0',
    'description': 'Client library for https://api.gsmtasks.com/ .',
    'long_description': 'None',
    'author': 'None',
    'author_email': 'None',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'https://github.com/lapidary-library/gsmtasks-client',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.9,<4.0',
}


setup(**setup_kwargs)
