
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T22:36:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0354bc7e0d3939187a12d0d9d048bf38cc4ac1fc",
 "version": "0.2.55.post0.dev20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
