
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T17:11:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bc1aa46a93abbc6cdb67ba516055a70a7407679",
 "version": "0.9.6.dev20221216"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
