
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T21:35:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3960a258094652b40775711548d73e6b0cdeb91",
 "version": "0.0.50.dev20221215"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
