
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T16:37:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "68728af6ea7ac653d8780e562c0ebfdabe61ab35",
 "version": "0.15.40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
