
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-12T11:55:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7de65e423f80110fe87beec8bf5c1018997b8cda",
 "version": "0.10.7b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
