# Generated by Lapidary.
# All manual changes will be lost!

from __future__ import annotations

import typing
import lapidary.runtime
import pydantic
import gsmtasks.components.schemas.level_enum
import lapidary.runtime.absent


class ConfigurationNotification(pydantic.BaseModel):
    level: typing.Annotated[
        gsmtasks.components.schemas.level_enum.LevelEnum, pydantic.Field()
    ]

    message: typing.Annotated[str, pydantic.Field()]

    url: typing.Annotated[
        typing.Union[
            str,
            None,
        ],
        pydantic.Field(),
    ]

    persist: typing.Annotated[
        typing.Union[
            bool,
            lapidary.runtime.absent.Absent,
        ],
        pydantic.Field(),
    ] = lapidary.runtime.absent.ABSENT

    open_in_new_window: typing.Annotated[
        typing.Union[
            bool,
            lapidary.runtime.absent.Absent,
        ],
        pydantic.Field(),
    ] = lapidary.runtime.absent.ABSENT

    class Config(pydantic.BaseConfig):
        use_enum_values = True
        extra = pydantic.Extra.allow


ConfigurationNotification.update_forward_refs()
