
# This yaml was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this yaml.

import json

version_json = '''
{
 "date": "2022-12-16T13:43:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9201b0e2ed20f338a3707442a03a2e60a8d3f198",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
