
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T17:14:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e6d40a600bfa64ea3ac11647076eabb6d2f4548",
 "version": "4.7.42"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
