
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T02:21:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3898c60f3034ab7224c7b443549826c678287c14",
 "version": "4.9.58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
