
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-13T23:31:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "62fc68cf2be461f6edcb42bac15b348829a63801",
 "version": "0.2.55.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
