
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-16T13:00:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "39931b479076cc70652867eb92e67e7f92475de0",
 "version": "0.1.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
