
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-15T09:54:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a5be905f578efdb2f16c5ffa84f99d30081acb8",
 "version": "4.7.43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
