"""
${schema.title} Object

${schema.description}

${schema.comment}

Autogenerated, do not edit.
"""

% if schema.import_statements:
% for imp in schema.import_statements:
${imp}
%endfor

%endif

class ${schema.name}(${schema.superclass_string}):
    """${schema.title}"""

    % for property in schema.properties:
    % for line in property.description:
    # ${line}
    % endfor
    ${property.definition}
    % endfor
